### ISSUE TITLE
Slides from Berlin Meetup

### ISSUE THREAD

**Issue by wojtasskorcz** [propensive/impromptu#3]
Hi Jon! As I don't have any other way to reach you, I'm creating this issue.

I really enjoyed your talk in Berlin and would like to introduce Impromptu to my colleagues. Would you be okay with sharing the slides from the talk? I thought your take on the introduction was spot on, I'd only have to simplify it a bit.

Thanks in advance!

**Comment by propensive** [comment]
Hi @wojtasskorcz - sorry that I missed this back in August! There are slides from a recent talk I gave in London, [here](http://jon.pretty.studio/talks/15-12-17-london/).

Sorry if I missed the boat on this...
